name: lainan-desktop-online
base: core18
version: "0.0.1"
description: "LainanDesktop Online is LaianDesktop Edition(Online)."

apps:
  electronApp:
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - unity7
      - x11
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electronApp:
    source: .
    plugin: dump
    stage-packages:
      - libnotify4
      - libnss3
      - libpcre3
      - libxss1
      - libxtst6
    after:
      - desktop-gtk2
