name: lainan-desktop-online # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: LainanDesktop Online # 79 char long summary
description: "_LainanDesktop Online_\n\nLainanのDesktop版がついにリリース！\n\nLinux版は、SnapStoreで。\nWindows版は、公式サイトにて配布予定。\n\nぜひ、毎日お使いくださいね！"

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  electron-packager-hello-world:
    command: lainan-desktop-online/lainan-desktop-online --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      # Chromium フレームワーク/Electron の TMPDIR パスを修正し、
      # libappindicator が読めるリソースを確保します。
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  lainan-desktop-online:
    plugin: nil
    source: .
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./lainan-desktop-online-linux-* $SNAPCRAFT_PART_INSTALL/lainan-desktop-online
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4