name: lainan-desktop-online
title: "Lainan Desktop"
base: core18
version: "0.0.14+git"
license: "MIT"
summary: LainanDesktop Online
description: |
  _LainanDesktop Online_

  LainanのDesktop版がついにリリース！

  Linux版は、SnapStoreで。
  Windows版は、公式サイトにて配布予定。

  ぜひ、毎日お使いくださいね！
icon: "app/icon/lainan_icon.svg"
grade: stable
confinement: strict

apps:
  electron-packager-hello-world:
    command: lainan-desktop-online/lainan-desktop-online --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      # Chromium フレームワーク/Electron の TMPDIR パスを修正し、
      # libappindicator が読めるリソースを確保します。
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  lainan-desktop-online:
    plugin: nil
    source: app/
    override-build: |
      npm install electron electron-packager
      npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
      cp -rv ./lainan-desktop-online-linux-* $SNAPCRAFT_PART_INSTALL/app/
    build-snaps:
      - node/14/stable
    build-packages:
      - unzip
    stage-packages:
      - libnss3
      - libnspr4
