name: lainan-desktop-online
title: "Lainan Desktop"
base: core18
version: "0.0.14+git"
license: "MIT"
summary: LainanDesktop Online
description: |
  _LainanDesktop Online_

  LainanのDesktop版がついにリリース！

  Linux版は、SnapStoreで。
  Windows版は、公式サイトにて配布予定。

  ぜひ、毎日お使いくださいね！
icon: "app/icon/lainan_icon.svg"
grade: stable
confinement: strict

apps:
  lainan-desktop-online:
    command: bin/desktop-launch $SNAP/app/lainan-desktop-online
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electron-quick-start:
    plugin: nil
    source: app/
    override-build: |
        npm install electron electron-builder
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
        npm run pack
        mkdir $SNAPCRAFT_PART_INSTALL/lainan-desktop-online
        cd release-builds/*/
        mv * $SNAPCRAFT_PART_INSTALL/lainan-desktop-online
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4